/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.boston2600.bluebox;

public final class R {
    public static final class array {
        public static final int toneTypes=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        public static final int buttonHeight=0x7f050001;
        public static final int buttonWidth=0x7f050000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int eight=0x7f090008;
        public static final int five=0x7f090005;
        public static final int four=0x7f090004;
        public static final int keypad=0x7f090000;
        public static final int keypulse=0x7f09000c;
        public static final int nine=0x7f090009;
        public static final int one=0x7f090001;
        public static final int seven=0x7f090007;
        public static final int six=0x7f090006;
        public static final int start=0x7f09000a;
        public static final int three=0x7f090003;
        public static final int trunk=0x7f09000d;
        public static final int two=0x7f090002;
        public static final int zero=0x7f09000b;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int blue_0=0x7f040000;
        public static final int blue_1=0x7f040001;
        public static final int blue_2=0x7f040002;
        public static final int blue_2600=0x7f040003;
        public static final int blue_3=0x7f040004;
        public static final int blue_4=0x7f040005;
        public static final int blue_5=0x7f040006;
        public static final int blue_6=0x7f040007;
        public static final int blue_7=0x7f040008;
        public static final int blue_8=0x7f040009;
        public static final int blue_9=0x7f04000a;
        public static final int blue_kp=0x7f04000b;
        public static final int blue_st=0x7f04000c;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
    }
    public static final class style {
        public static final int keypadButton=0x7f080000;
        public static final int keypadText=0x7f080001;
    }
}
